<?php /** @var Firegento_FlexCms_Block_Adminhtml_Catalog_Form_Popup $this */ ?>

<div class="firegento-flexcms-changes">
    <?php $messages = $this->getMessages() ?>
    <?php if (sizeof($messages)): ?>
        <ul class="messages">
        <?php foreach($messages as $message): ?>
            <li class="notice-msg">
                <strong><?php echo $message->getAdminUser()->getFirstname() . ' ' . $message->getAdminUser()->getLastname() ?></strong>
                (<?php echo $message->getFormattedDate() ?>):<br />
                <?php echo nl2br($message->getText()) ?>
            </li>
        <?php endforeach ?>
        </ul>
    <?php endif ?>
</div>

<div id="request_publish_popup" class="firegento-flexcms-popup">
    <form id="request_publish" action="<?php echo $this->getRequestPublishPostUrl() ?>" method="post">
        <div class="no-display">
            <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
            <input name="category_id" type="hidden" value="<?php echo $this->getCategory()->getId() ?>" />
            <input name="store_id" type="hidden" value="<?php echo $this->getCategory()->getStoreId() ?>" />
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tbody>
                <tr>
                    <td class="label">
                        <label for="publisher"><?php echo $this->__('Send Request to') ?>:<span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <?php echo $this->getPublisherHtmlSelect() ?>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="comment"><?php echo $this->__('Comment') ?>:</label>
                    </td>
                    <td class="value">
                        <textarea name="comment" id="comment"></textarea>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <p class="content-buttons">
            <button type="submit">
                <span><span><?php echo $this->__('Send Request') ?></span></span>
            </button>
        </p>
    </form>
</div>

<script type="text/javascript">
    var requestPublishForm = new varienForm('request_publish');
</script>